POST http://localhost:54572/api/order HTTP/1.1
content-type: application/json

{
    "data": {
        "orderId": "{{$randomInt 10 1000}}"
    }
}

###
POST http://localhost:54572/v1.0/invoke/service1/method/order HTTP/1.1
content-type: application/json

{
    "data": {
        "orderId": "{{$randomInt 10 1000}}"
    }
}

###

POST http://localhost:3500/v1.0/invoke/nodeapp/method/neworder HTTP/1.1
content-type: application/json

{
    "data": {
        "orderId": "{{$randomInt 10 1000}}"
    }
}