# tye application configuration file
# read all about it at https://github.com/dotnet/tye
#
# when you've given us a try, we'd love to know what you think:
#    https://aka.ms/AA7q20u
#
name: poc
extensions:
- name: dapr
  log-level: debug
  config: ./dapr/configuration/configuration.yaml
  components-path: "./dapr/components"

  # - name: zipkin
  # - name: elastic
  #   logPath: ./.logs

services:
- name: pubsub-service1
  project: Service1/Service1.csproj
  bindings: 
  - port: 15000
- name: pubsub-service2
  project: Service2/Service2.csproj
- name: pubsub-service3
  project: Service3/Service3.csproj
- name: redis
  image: redis
  bindings: 
  - port: 6379
- name: zipkin
  image: openzipkin/zipkin
  bindings: 
  - port: 9411

# NOTE:
# if dapr --init was not run, uncomment the redis service
# - name: redis
#   image: redis
#   bindings: 
#   - port: 6379
# - name: zipkin
#   image: openzipkin/zipkin
#   bindings: 
#   - port: 9411